### ISSUE TITLE
URL:s ending with an asterisk isn't found when searching for the same URL

### ISSUE THREAD

**Issue by krakan** [nla/outbackcdx#112]
We have an OutbackCDX collection with a URL ending with an asterisk (`*`):
```
se,emnordic)/varumarke?cms_searchstring=*&productbrandfamily=multimediaholders2&productbrandfamily=vtseries&type=products 20170901165831 http://www.emnordic.se/varumarke?Type=Products&Productbrandfamily=multimediaholders2&Productbrandfamily=vtseries&CMS_SearchString=* text/html 200 B2YAZ73DHPERWZAUXYT7I2KLMKQSOLRS - - 124649 1388 Svep/2017-1/09/SWE-KB-KW3-BULK-2017-1-20170901165831-05061-srvvm303.kb.se.warc.gz
```
For simplicity I created a new collection and added some test data:

```
curl -sSfX POST --data-binary "se,foo)?baz=*&foo=bar 20220822 http://www.foo.se/?foo=bar&baz=* text/html 200 ABCDE - - 12345 123 archive.warc.gz" http://localhost:8085/other
curl -sSfX POST --data-binary "se,foo)?baz=1&foo=bar 20220822 http://www.foo.se/?foo=bar&baz=1 text/html 200 ABCDE - - 12345 123 archive.warc.gz" http://localhost:8085/other
curl -sSfX POST --data-binary "se,foo)?bar=baz&foo=* 20220822 http://www.foo.se/?bar=baz&foo=* text/html 200 ABCDE - - 12345 123 archive.warc.gz" http://localhost:8085/other
```

Searching for it with the original URL yields no result:
```
curl -sSfG 'http://localhost:8085/other' --data-urlencode 'url=http://www.foo.se/foo=bar&baz=*'
```
but appending an extra ampersand makes the search work:
```
curl -sSfG 'http://localhost:8085/other' --data-urlencode 'url=http://www.foo.se/?foo=bar&baz=*&'
```
Also reordering the parameters so that the URL doesn't end with the asterisk as well as replacing the asterisk with `%2A` (which would then be encoded again to `%252A` as we use the curl option `--data-urlencode`) works:
```
curl -sSfG 'http://localhost:8085/other' --data-urlencode 'url=http://www.foo.se/?baz=*&foo=bar
curl -sSfG 'http://localhost:8085/other' --data-urlencode 'url=http://www.foo.se/?foo=bar&baz=%2A
```

Note also that the second and third lines of test data don't have the same problem.

Searching in Pywb gives the same results so this does not appear to be a curl issue.

**Comment by ato** [comment]
This is a consequence of the wildcard syntax in the [pywb cdxserver protocol](https://pywb.readthedocs.io/en/latest/manual/cdxserver_api.html#matchtype) which OutbackCDX tries to be compatible with:

> As a shortcut, instead of specifying a separate matchType parameter, wildcards may be used in the url:
>
>  `...?url=http://example.com/path/*` is equivalent to `...?url=http://example.com/path/&matchType=prefix`
> `...?url=*.example.com` is equivalent to `...?url=example.com&matchType=domain`

You can disable the expansion of wildcards by specifying `matchType=exact` explicitly:

```sh
$ curl -sSfG 'http://localhost:8085/other' --data-urlencode 'url=http://www.foo.se/?foo=bar&baz=*' -d matchType=exact
se,foo)/?baz=*&foo=bar 20220822000000 http://www.foo.se/?foo=bar&baz=* text/html 200 ABCDE=== - - 12345 123 archive.warc.gz
```

Note that the "Searching for it with the original URL" example is also missing the ? character indicating the start of the query string.

**Comment by ato** [comment]
> Searching in Pywb gives the same results

Maybe we should be configuring pywb differently to ensure it passes matchType explicitly, I wonder if adding matchType=exact to the URL template in the config would work or if that would break matchType=prefix queries.

I would also assume this also affects pywb when configured to use pywb's own cdxserver implementation as it should behave the same way.

**Comment by krakan** [comment]
Yes, I just checked and pywb behaves just the same with local indexes. And yes, your explanation makes sense. But I think it would also make sense to have a search without matchType to always be equivalent with matchType=exact - or at least that was what I expected even though I knew about wildcard matches.

Also I would have expected `http://www.foo.se/?foo=bar&baz=*` to match itself but it appear that wildcard (and prefix) searches only works with the URL parameters in alphabetic order - i.e. `http://www.foo.se/?baz*` matches `http://www.foo.se/?foo=bar&baz=...` whereas `http://www.foo.se/?foo*` doesn't.

Either way, this is not an OutbackCDX issue then, but perhaps a Pywb issue that wildcard matches works weirdly with URL-parameters. I'll just close this issue as it is really an edge case.

Thank you for the explanation. And thank you for OutbackCDX!
