### ISSUE TITLE
Possible problem with escaping URLs in the OpenSearch API

### ISSUE THREAD

**Issue by anjackson** [nla/outbackcdx#12]
Firstly, note that the following issue is being seen on an older version of OutbackCDX (back when it was called tinycdxserver, appears to be at 54cb410653ba57a952fd28f7cae204ed7679e96c). This may have been fixed, in which case we'd like to know if just updating OubackCDX should work against the existing index files?

The actual issue is that we're hitting oddities with URLs with `+` in them. e.g.

    http://www.nta.nhs.uk/wEWAwLA/fRFApntjN0KAqWf8+4KhJYyV8tPyOxKMnDpaBxSb/scripts/css/css/css/404-error.aspx
    http://www.qie.eoe.nhs.uk/SearchResults.aspx?tmName=EMERGENCY+MEDICAL+CARE&geocode=Q35&pubnameexact=NCHOD

If you query directly, like this:

    http://192.168.45.21:8080/data-heritrix?url=http%3A%2F%2Fwww.qie.eoe.nhs.uk%2FSearchResults.aspx%3FtmName%3DEMERGENCY%2BMEDICAL%2BCARE%26geocode%3DQ35%26pubnameexact%3DNCHOD

we see the results we expect. But if you use the OpenSearch API

    http://192.168.45.21:8080/data-heritrix?q=type:urlquery+url:http%3A//www.qie.eoe.nhs.uk/SearchResults.aspx%3FtmName%3DEMERGENCY%2BMEDICAL%2BCARE%26geocode%3DQ35%26pubnameexact%3DNCHOD

we get 

    <?xml version="1.0" encoding="UTF-8"?><wayback><error><title>Resource Not In Archive</title><message>The Resource you requested is not in this archive.</message></error></wayback>

Also, if I avoid escaping the `+` the server goes 500 with an `ArrayIndexOutOfBoundsException`.

Also, if you attempt to use normal Python requests escaping for the `q` parameter, the whole thing fails because the `q=type:urlquery+url:...` escape the colons and space etc. Not sure that's incorrect though - I just don't know the OpenSearch spec. well enough to be sure.

**Comment by ato** [comment]
Surprisingly Wayback actually encodes twice when constructing the open search query URL. In Python I think it'd be something like this:

```python
from urllib import quote_plus # python 2
#from urllib.parse import quote_plus # python 3

url = "http://www.qie.eoe.nhs.uk/SearchResults.aspx?tmName=EMERGENCY+MEDICAL+CARE&geocode=Q35&pubnameexact=NCHOD"
q = "type:urlquery url:" + quote_plus(url)
cdx_query_url = "http://192.168.45.21:8080/data-heritrix?q=" + quote_plus(q)
```

The specific encoding is the one documented in the Java [URLEncoder](https://docs.oracle.com/javase/7/docs/api/java/net/URLEncoder.html) class.

There's an open issue (#7) to try to detect this and add better error messaging as this trips everyone up from time to time.

**Comment by anjackson** [comment]
Thanks @ato - I'll close this one in deference to #7
