### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by omgoo** [nla/outbackcdx#122]
Would it be possible to start using releases and version numbers? With 1,481 additions and 597 deletions on master since the last release, it's clear we need to be using a newer version. However without a proper release schedule we cant be sure that we are going to be using stable code. Thanks

**Comment by ato** [comment]
I've made a release of the current code. https://github.com/nla/outbackcdx/releases/tag/1.0.0

I was holding off on releasing as I thought the index version upgrade process probably needs to be more friendly but it works okay and realistically we have too many other priorities at the moment.
