### ISSUE TITLE
Handling malformed URIs

### ISSUE THREAD

**Issue by anjackson** [nla/outbackcdx#15]
We hit an odd edge case. We ended up checking OutbackCDX for some weird URIs thrown up by the crawl, like:

```
http://allprintjerseyyourlocalembroideryandvinylprintspecialisthomepage/
http://development-social-marketing-strategy-promote-ebola-treatment-seeking-behaviour-sierra-leone/
```

When querying OutbackCDX, this cause a runtime exception in [IDN.toASCII](https://github.com/nla/outbackcdx/blob/84bacd5a47f348aeec5e75f2ee48358d36312dcc/src/outbackcdx/UrlCanonicalizer.java#L168):

```
java.lang.IllegalArgumentException: The label in the input is too long
```
Because the domain label is greater than the 63 characters allowed.

Admittedly this is because we're kind of misusing OubackCDX as a crawl status database, rather than a playback index.

That said, would it be worth returning a `400 Bad Request` rather than `500`? Is there a more elegant way to handle this?

**Comment by ato** [comment]
Hm. I'm tempted to just catch the exception and continue canonicalization. What do you think?

**Comment by anjackson** [comment]
Ah, good idea! I can't see that that would cause a problem, and it would make the client code simpler.
