### ISSUE TITLE
Report exception to client in WbCdxApi

### ISSUE THREAD

**Issue by ato** [nla/outbackcdx#84]
At the moment if a WbCdxApi query throws an exception the query results are truncated. While we can't switch status codes as we've already returned the header and are streaming results we could print a message so its at least obvious to humans that something's gone wrong. We could also maybe use chunked-encoding and close early although some http clients might still not treat that as an error.

**Comment by galgeek** [comment]
Is there a good way to report an exception to all clients?

Logging the error on the server would be helpful.  PR #86 would be a minimal fix, I think.

**Comment by ato** [comment]
Returning an intentionally invalid line might be the best option I guess
